"""
GridLang JS bundler — packages a ``.grid`` file's data + compute layer into
a self-contained JavaScript bundle that runs anywhere a JS engine does.

Two output flavours:

* **Node bundle** (default) — runs as ``node bundle.js`` and prints the
  pipeline result as JSON on stdout. Useful for running the compute layer in
  a CI job that has Node but not Python, or for sharing a reproducible
  pipeline with frontend teammates.

* **Browser bundle** (``--browser``) — emits a self-contained Web Worker
  source that listens on ``onmessage`` and answers with the pipeline result.
  This is the building block for running ``.grid`` files entirely in the
  browser; an HTML harness can spawn it as ``new Worker(URL.createObjectURL(blob))``.

Both bundles embed the data, the user's compute code, the ``df_helpers.js``
prelude, and the ``runtime_pipeline.js`` runner verbatim — no Node-side
``require`` chain at runtime, no external CDN, no ESM resolver. The output
is a single self-contained ``.js`` file that can be ``cat``'d.

Bundle layout (Node)::

    /* GridLang Node bundle generated by gridlang js-bundle */
    (function () {
      const REQUEST = {df, sheets, is_multi_sheet};
      <df_helpers.js>
      <runtime_pipeline.js>
      const __scope = {};
      (function() { /* user code, with 'this' bound to __scope */ }).call(__scope);
      const result = runPipeline(REQUEST, __scope);
      process.stdout.write(JSON.stringify(result, null, 2) + '\\n');
    })();
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd

from gridlang.parser import GridDocument, parse_file, parse_string
from gridlang.data_sources import load_dataframes
from gridlang.js_runtime import (
    get_helpers_source,
    _df_to_records,
    _json_default,
)


# ─── Source loading ────────────────────────────────────────────────────────

_JS_DIR = Path(__file__).parent / 'js'
_PIPELINE_PATH = _JS_DIR / 'runtime_pipeline.js'


def _read(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def get_pipeline_source() -> str:
    """Public — return the contents of runtime_pipeline.js."""
    return _read(_PIPELINE_PATH)


# ─── Bundle assembly ───────────────────────────────────────────────────────

@dataclass
class BundleResult:
    """Output of a bundle operation."""
    source: str            # the assembled JS bundle text
    target: str            # 'node' or 'browser'
    bytes: int             # len(source)
    sheet_count: int


def bundle_doc(
    doc: GridDocument,
    *,
    target: str = 'node',
    pretty: bool = True,
    allow_remote: bool = False,
) -> BundleResult:
    """
    Bundle a parsed GridDocument into a self-contained JS file.

    Args:
        doc:          A parsed GridDocument. Must declare ``engine: javascript``.
        target:       ``'node'`` (default) or ``'browser'``.
        pretty:       If True, indent JSON for readability (~3x bundle size).
        allow_remote: Forwarded to load_dataframes for ``@source`` directives.
    """
    if doc.engine != 'javascript':
        raise ValueError(
            f"bundle_doc: document declares engine={doc.engine!r}; "
            f"only engine: javascript is bundleable."
        )
    if target not in ('node', 'browser'):
        raise ValueError(f"target must be 'node' or 'browser', got {target!r}")

    sheets, _ = load_dataframes(doc, allow_remote=allow_remote)

    # Build the JSON request payload exactly the way the Node bridge expects.
    sheets_records = {k: _df_to_records(v) for k, v in sheets.items()}
    primary_records = list(sheets_records.values())[0] if sheets_records else []
    request = {
        'df': primary_records,
        'sheets': sheets_records,
        'is_multi_sheet': len(sheets) > 1,
        'meta': {
            'name': doc.meta.get('name', 'Untitled'),
            'engine': 'javascript',
            'version': doc.meta.get('version', '1.0'),
        },
    }
    indent = 2 if pretty else None
    request_json = json.dumps(request, indent=indent, default=_json_default)

    if target == 'node':
        source = _build_node_bundle(request_json, doc.compute_raw)
    else:
        source = _build_browser_bundle(request_json, doc.compute_raw)

    return BundleResult(
        source=source,
        target=target,
        bytes=len(source),
        sheet_count=len(sheets),
    )


def bundle_file(
    grid_path: str | Path,
    *,
    target: str = 'node',
    pretty: bool = True,
    allow_remote: bool = False,
) -> BundleResult:
    """Convenience wrapper: parse a .grid file, then bundle it."""
    doc = parse_file(grid_path)
    return bundle_doc(doc, target=target, pretty=pretty, allow_remote=allow_remote)


# ─── Bundle templates ─────────────────────────────────────────────────────

def _build_node_bundle(request_json: str, user_code: str) -> str:
    """Assemble the Node bundle text."""
    helpers = get_helpers_source()
    pipeline = get_pipeline_source()
    return (_NODE_TEMPLATE
            .replace('__REQUEST__', request_json)
            .replace('__HELPERS__', helpers)
            .replace('__PIPELINE__', pipeline)
            .replace('__USER_CODE__', user_code))


def _build_browser_bundle(request_json: str, user_code: str) -> str:
    """Assemble the Browser/Worker bundle text."""
    helpers = get_helpers_source()
    pipeline = get_pipeline_source()
    return (_BROWSER_TEMPLATE
            .replace('__REQUEST__', request_json)
            .replace('__HELPERS__', helpers)
            .replace('__PIPELINE__', pipeline)
            .replace('__USER_CODE__', user_code))


# Templates use literal placeholders so user-supplied JS can contain any
# characters (braces, %, $) without escaping. .format() would mangle them.

_NODE_TEMPLATE = r"""// GridLang Node bundle — generated by `gridlang js-bundle`
// Run as: node thisfile.js
// Outputs the pipeline result as JSON on stdout.

const REQUEST = __REQUEST__;

// ─── df helpers ────────────────────────────────────────────────────────────
__HELPERS__

// ─── pipeline runner ──────────────────────────────────────────────────────
__PIPELINE__

// ─── user compute layer ───────────────────────────────────────────────────
const __scope = Object.create(null);
(function() {
__USER_CODE__
  // Re-export top-level definitions onto __scope.
  for (const fn of ['validate', 'transform', 'aggregates', 'conditional_formats']) {
    try {
      const v = eval(fn);
      if (typeof v === 'function') __scope[fn] = v;
    } catch (_e) { /* not defined */ }
  }
}).call(__scope);

const result = runPipeline(REQUEST, __scope);
process.stdout.write(JSON.stringify(result, null, 2) + '\n');
"""


_BROWSER_TEMPLATE = r"""// GridLang Browser/Worker bundle — generated by `gridlang js-bundle --browser`
// Use as:
//   const w = new Worker(URL.createObjectURL(new Blob([bundleSource], {type:'application/javascript'})));
//   w.onmessage = e => console.log(e.data);
//   w.postMessage('run');
//
// Or load via <script> and call runGridLangPipeline() on the global.

(function (root) {
  const REQUEST = __REQUEST__;

  // ─── df helpers ──────────────────────────────────────────────────────────
__HELPERS__

  // ─── pipeline runner ────────────────────────────────────────────────────
__PIPELINE__

  // ─── user compute layer ─────────────────────────────────────────────────
  const __scope = Object.create(null);
  (function() {
__USER_CODE__
    for (const fn of ['validate', 'transform', 'aggregates', 'conditional_formats']) {
      try {
        const v = eval(fn);
        if (typeof v === 'function') __scope[fn] = v;
      } catch (_e) { /* not defined */ }
    }
  }).call(__scope);

  function runGridLangPipeline(overrideRequest) {
    return runPipeline(overrideRequest || REQUEST, __scope);
  }

  // Worker mode — listen for messages.
  if (typeof self !== 'undefined' && typeof self.addEventListener === 'function') {
    self.addEventListener('message', function(ev) {
      const result = runGridLangPipeline(ev.data && ev.data.request);
      self.postMessage(result);
    });
  }

  // Browser global.
  if (typeof root !== 'undefined') {
    root.runGridLangPipeline = runGridLangPipeline;
    root.GRIDLANG_REQUEST = REQUEST;
  }
})(typeof self !== 'undefined' ? self : (typeof globalThis !== 'undefined' ? globalThis : this));
"""
