// gridlang/js/runtime_pipeline.js — Engine-agnostic pipeline runner.
//
// Used by both the Node bundle and the Web Worker bundle generated by
// `gridlang js-bundle`. Takes a request object with the same shape as the
// Python ↔ Node bridge wire format and returns a response object.
//
// This file expects `makeDF` to already be in scope (loaded from
// df_helpers.js) and `compute` (the user's JS code source as a string) to
// be available via the host module. The host wires up the IO.

function runPipeline(req, hostScope) {
  // hostScope is the object onto which user code's transform/aggregates/etc.
  // were defined when the user code ran.
  const isMulti = !!req.is_multi_sheet;

  const found = [];
  for (const fn of ['validate', 'transform', 'aggregates', 'conditional_formats']) {
    if (typeof hostScope[fn] === 'function') found.push(fn);
  }

  // Step 1: validate
  let validationMessages = [];
  if (typeof hostScope.validate === 'function') {
    try {
      const messages = hostScope.validate(makeDF((req.df || []).slice()));
      if (messages && messages.length) {
        validationMessages = Array.isArray(messages) ? messages : [String(messages)];
        return {
          error: 'Validation failed:\n' + validationMessages.map(m => '  - ' + m).join('\n'),
          validation_messages: validationMessages,
        };
      }
    } catch (e) {
      return { error: 'Error in validate(): ' + (e && e.message || String(e)) };
    }
  }

  // Step 2: transform
  let resultDf = req.df || [];
  let resultSheets = req.sheets || { default: req.df || [] };

  if (typeof hostScope.transform === 'function') {
    const fnSrc = hostScope.transform.toString();
    const paramMatch = fnSrc.match(/function[^(]*\(([^)]*)\)|\(([^)]*)\)\s*=>/);
    const firstParam = ((paramMatch && (paramMatch[1] || paramMatch[2])) || '').split(',')[0].trim();
    const wantsSheets = isMulti && (firstParam === 'sheets' || firstParam === 'dfs');

    try {
      if (wantsSheets) {
        const sheets = {};
        for (const k of Object.keys(req.sheets || {})) {
          sheets[k] = makeDF((req.sheets[k] || []).slice());
        }
        const out = hostScope.transform(sheets);
        if (out === undefined) {
          return { error: 'Error in transform(): transform() returned undefined; did you forget to return sheets?' };
        }
        const flat = {};
        for (const k of Object.keys(out)) flat[k] = Array.from(out[k] || []);
        resultSheets = flat;
        const firstKey = Object.keys(flat)[0];
        resultDf = firstKey ? flat[firstKey] : [];
      } else {
        const df = makeDF((req.df || []).slice());
        const out = hostScope.transform(df);
        if (out === undefined) {
          return { error: 'Error in transform(): transform() returned undefined; did you forget to return df?' };
        }
        resultDf = Array.from(out);
        resultSheets = { default: resultDf };
      }
    } catch (e) {
      return { error: 'Error in transform(): ' + (e && e.message || String(e)) };
    }
  }

  // Step 3: aggregates
  let agg = {};
  if (typeof hostScope.aggregates === 'function') {
    try {
      const out = hostScope.aggregates(makeDF(resultDf.slice()));
      if (out !== null && out !== undefined) {
        if (typeof out !== 'object' || Array.isArray(out)) {
          return { error: 'aggregates() must return an object, got ' + typeof out };
        }
        agg = out;
      }
    } catch (e) {
      return { error: 'Error in aggregates(): ' + (e && e.message || String(e)) };
    }
  }

  // Step 4: conditional_formats
  let condFormats = [];
  if (typeof hostScope.conditional_formats === 'function') {
    try {
      const out = hostScope.conditional_formats();
      if (Array.isArray(out)) {
        condFormats = out.filter(r => r && typeof r === 'object');
      }
    } catch (e) {
      return { error: 'Error in conditional_formats(): ' + (e && e.message || String(e)) };
    }
  }

  return {
    df: resultDf,
    sheets: resultSheets,
    aggregates: agg,
    conditional_formats: condFormats,
    validation_messages: validationMessages,
    found_functions: found,
    error: null,
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { runPipeline };
}
